import { inverterCatalogSchema, type InverterCatalogItem } from '@/core/schemas/inverterSchema';

export type Inverter = InverterCatalogItem;

export const INVERTER_CATALOG: Inverter[] = inverterCatalogSchema.parse([
  {
    id: 'inv-growatt-75k',
    manufacturer: 'Growatt',
    model: 'MAX 75KTL3 LV',
    nominalPowerW: 75000,
    maxDCPowerW: 112500,
    efficiency: { euro: 98.5 },
    maxInputVoltage: 1100,
    mppts: Array.from({ length: 6 }, (_, i) => ({
      mpptId: i + 1,
      minMpptVoltage: 200,
      maxMpptVoltage: 1000,
      maxInputVoltage: 1100,
      maxCurrentPerMPPT: 40,
      stringsAllowed: 2,
    })),
  },
  {
    id: 'inv-deye-50k',
    manufacturer: 'Deye',
    model: 'SUN-50K-G03',
    nominalPowerW: 50000,
    maxDCPowerW: 75000,
    efficiency: { euro: 98.7 },
    maxInputVoltage: 1000,
    mppts: Array.from({ length: 4 }, (_, i) => ({
      mpptId: i + 1,
      minMpptVoltage: 200,
      maxMpptVoltage: 850,
      maxInputVoltage: 1000,
      maxCurrentPerMPPT: 55,
      stringsAllowed: 2,
    })),
  },
  {
    id: 'inv-fronius-tauro-50',
    manufacturer: 'Fronius',
    model: 'Tauro Eco 50-3-D',
    nominalPowerW: 50000,
    maxDCPowerW: 75000,
    efficiency: { euro: 98.5 },
    maxInputVoltage: 1000,
    mppts: [
      {
        mpptId: 1,
        minMpptVoltage: 580,
        maxMpptVoltage: 930,
        maxInputVoltage: 1000,
        maxCurrentPerMPPT: 100,
        stringsAllowed: 4,
      },
    ],
  },
  {
    id: 'inv-sungrow-125k',
    manufacturer: 'Sungrow',
    model: 'SG125CX',
    nominalPowerW: 125000,
    maxDCPowerW: 187500,
    efficiency: { euro: 99.0 },
    maxInputVoltage: 1100,
    mppts: Array.from({ length: 12 }, (_, i) => ({
      mpptId: i + 1,
      minMpptVoltage: 180,
      maxMpptVoltage: 1000,
      maxInputVoltage: 1100,
      maxCurrentPerMPPT: 35,
      stringsAllowed: 2,
    })),
  },
  {
    id: 'inv-micro-aps-ds3',
    manufacturer: 'APSystems',
    model: 'DS3-LV',
    nominalPowerW: 880,
    maxDCPowerW: 1100,
    efficiency: { euro: 97.0 },
    maxInputVoltage: 60,
    mppts: Array.from({ length: 2 }, (_, i) => ({
      mpptId: i + 1,
      minMpptVoltage: 28,
      maxMpptVoltage: 45,
      maxInputVoltage: 60,
      maxCurrentPerMPPT: 25,
      stringsAllowed: 1,
    })),
  },
  {
    id: 'inv-phb-15k-mt',
    manufacturer: 'PHB',
    model: '15K-MT',
    nominalPowerW: 15000,
    maxDCPowerW: 22500,
    efficiency: { euro: 98.2 },
    mppts: [
      { mpptId: 1, minMpptVoltage: 200, maxMpptVoltage: 800, maxInputVoltage: 800, maxCurrentPerMPPT: 25.0, stringsAllowed: 2 },
      { mpptId: 2, minMpptVoltage: 200, maxMpptVoltage: 800, maxInputVoltage: 800, maxCurrentPerMPPT: 25.0, stringsAllowed: 2 },
    ],
  },
  {
    id: 'inv-phb-20k-mt',
    manufacturer: 'PHB',
    model: '20K-MT',
    nominalPowerW: 20000,
    maxDCPowerW: 30000,
    efficiency: { euro: 98.3 },
    mppts: [
      { mpptId: 1, minMpptVoltage: 200, maxMpptVoltage: 800, maxInputVoltage: 800, maxCurrentPerMPPT: 25.0, stringsAllowed: 2 },
      { mpptId: 2, minMpptVoltage: 200, maxMpptVoltage: 800, maxInputVoltage: 800, maxCurrentPerMPPT: 25.0, stringsAllowed: 2 },
    ],
  },
  {
    id: 'inv-phb-36k-mt',
    manufacturer: 'PHB',
    model: '36K-MT',
    nominalPowerW: 36000,
    maxDCPowerW: 54000,
    efficiency: { euro: 98.4 },
    mppts: [
      { mpptId: 1, minMpptVoltage: 200, maxMpptVoltage: 800, maxInputVoltage: 1100, maxCurrentPerMPPT: 25.0, stringsAllowed: 2 },
      { mpptId: 2, minMpptVoltage: 200, maxMpptVoltage: 800, maxInputVoltage: 1100, maxCurrentPerMPPT: 25.0, stringsAllowed: 2 },
      { mpptId: 3, minMpptVoltage: 200, maxMpptVoltage: 800, maxInputVoltage: 1100, maxCurrentPerMPPT: 25.0, stringsAllowed: 2 },
    ],
  },
  {
    id: 'inv-phb-50k-mt',
    manufacturer: 'PHB',
    model: '50K-MT',
    nominalPowerW: 50000,
    maxDCPowerW: 75000,
    efficiency: { euro: 98.4 },
    mppts: [
      { mpptId: 1, minMpptVoltage: 200, maxMpptVoltage: 800, maxInputVoltage: 800, maxCurrentPerMPPT: 44.0, stringsAllowed: 4 },
      { mpptId: 2, minMpptVoltage: 200, maxMpptVoltage: 800, maxInputVoltage: 800, maxCurrentPerMPPT: 44.0, stringsAllowed: 4 },
      { mpptId: 3, minMpptVoltage: 200, maxMpptVoltage: 800, maxInputVoltage: 800, maxCurrentPerMPPT: 44.0, stringsAllowed: 4 },
    ],
  },
]);
